### PR TITLE
add search key requirement

### PR DESCRIPTION
**Pull request by meetar**

### CODE REVIEW

**Comment by robhawkes** [comment]
The other option here is to define the Pelias key within `config.js` and use it site-wide, which is probably a good idea otherwise we risk hitting rate limits unnecessary if we don't use a key for everything that isn't a batch upload. This would also mean no need to pass any keys in the batch uploader.

This would likely require something adding to Chef, though I don't know how the config options have been set up there. Hopefully that doesn't require too much effort.

What do you think?

**Comment by meetar** [comment]
Fine with me, and if you'd like to give wrangling Chef a go then more power to you :)

**Comment by robhawkes** [comment]
Alright, I'll give it a stab. I had a quick look and I can see where I'd add the config variable in the Chef template, but I'm not sure where I'd define / add the actual key value – do you have access to that bit? I don't have a background with Chef.

**Comment by meetar** [comment]
cc @baldur

**Pull request closed without merging**
